/*
 * @file afsctool_fullversion.h
 * Copyright 2017 René J.V. Bertin
 * This code is made available under the CPOL License
 * http://www.codeproject.com/info/cpol10.aspx
 */

#ifndef AFSCTOOL_FULLVERSION_H
#define AFSCTOOL_FULLVERSION_H

/* afsctool_fullversion.h.  Generated by cmake from afsctool_fullversion.h.cmake */

#define AFSCTOOL_FULL_VERSION_STRING "@afsctool_FULL_VERSION@"

#endif //  AFSCTOOL_FULLVERSION_H
